name: Unity Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Unity dependencies
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      # Build for Android
      - name: Build Android
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.2.5f1
          targetPlatform: Android

      # Build for Windows
      - name: Build Windows
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.2.5f1
          targetPlatform: StandaloneWindows64

      # Upload APK artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: Abay-Android
          path: build/Android/Android.apk

      # Upload EXE artifact
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v3
        with:
          name: Abay-Windows
          path: build/StandaloneWindows64/Abay.exe
